<a href="https://colab.research.google.com/github/byronacunia/Linear/blob/main/Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Read Data

In [1]:
!git clone https://github.com/byronacunia/Linear.git

Cloning into 'Linear'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 17 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (17/17), done.


In [71]:
import pandas as pd

In [72]:
X =  pd.read_csv("/content/Linear/X_DF.csv")
y =  pd.read_csv("/content/Linear/Y_DF.csv")

In [73]:
X.shape

(1500, 689)

In [74]:
y.shape

(1500, 398)

In [75]:
import numpy as np
from sklearn.model_selection import train_test_split

In [181]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [182]:
H.shape

(398, 690)

In [183]:
H = np.zeros((y_train.shape[1], X_train.shape[1]+1)) # Pre-allocate matrix

In [184]:
for i in range(y_train.shape[1]):
  ytreino=y_train.iloc[:, [i]].to_numpy()
  biass = np.ones((X_train.shape[0],1))
  phi = np.hstack((biass, X_train))
  w = np.linalg.lstsq(np.matmul(phi.T,phi), np.matmul(phi.T,ytreino),rcond=None)
  row=w[0]
  h=row.reshape(row.shape[1],row.shape[0])
  H[i,:] = h

In [185]:
H

array([[ 2.73295718e-03,  7.72003997e-04,  8.29860794e-04, ...,
         5.43129227e-05,  6.06618242e-05,  5.87290554e-05],
       [ 2.73224095e-03,  7.99536284e-04,  8.32709838e-04, ...,
         5.43990659e-05,  6.02578573e-05,  5.89150188e-05],
       [ 2.73294375e-03,  7.95320682e-04,  8.36746296e-04, ...,
         5.46652762e-05,  6.04502719e-05,  5.86093407e-05],
       ...,
       [-1.28264114e-05, -2.99327321e-06, -3.28407869e-06, ...,
        -2.42421265e-07, -2.52428183e-07, -2.47150475e-07],
       [-6.31824610e-05, -1.63938766e-05, -1.77302424e-05, ...,
        -1.22333832e-06, -1.33360986e-06, -1.29355666e-06],
       [ 3.75565831e-05,  1.08358973e-05,  1.18740438e-05, ...,
         7.46591896e-07,  8.21770090e-07,  7.95633917e-07]])

In [218]:
y_test.shape

(495, 398)

In [235]:
YPredictions = np.zeros((y_test.shape[1], y_test.shape[0])) # Pre-allocate matrix

In [236]:
for i in range(X_test.shape[0]):
  xTeste=X_test.iloc[[i],:].to_numpy()
  xTeste=np.vstack((1,xTeste.reshape(xTeste.shape[1],xTeste.shape[0])))
  y_pred=np.matmul(H,xTeste)
  YPredictions[:,i] = y_pred.reshape(y_pred.shape[0])

In [237]:
YPredictions

array([[6579.83312283, 6580.29187446, 6580.40170223, ..., 6580.34467033,
        6580.54013723, 6580.99399453],
       [6579.75338867, 6580.37055911, 6580.46933251, ..., 6580.34665305,
        6580.5207735 , 6580.91479451],
       [6579.80814469, 6580.3018605 , 6580.461427  , ..., 6580.40656563,
        6580.6103261 , 6580.9331344 ],
       ...,
       [ -30.05057011,  -30.04197904,  -30.03697256, ...,  -30.042288  ,
         -30.0360803 ,  -30.02463369],
       [-150.04943291, -150.04000237, -150.03488319, ..., -150.04042817,
        -150.03450448, -150.0246883 ],
       [  89.95111966,   89.95882718,   89.96439523, ...,   89.95972698,
          89.96601156,   89.97585975]])

In [212]:
yteste=y_test.iloc[[0],:].to_numpy()

In [215]:
yteste=yteste.reshape(yteste.shape[1],yteste.shape[0])

In [211]:
y_pred.shape

(398, 1)

In [208]:
from sklearn.metrics import explained_variance_score

In [216]:
explained_variance_score(yteste, y_pred)

0.9999801725177312

In [189]:
xTeste

array([[ 1.        ],
       [75.96277614],
       [61.07508912],
       [54.23482152],
       [43.74569572],
       [66.02032311],
       [63.45591551],
       [62.58661896],
       [80.18328792],
       [58.99501334],
       [54.37228907],
       [63.20379566],
       [52.32168812],
       [51.05889795],
       [53.97306204],
       [75.88460578],
       [48.69961145],
       [51.00478885],
       [64.11299514],
       [37.79057655],
       [65.28030786],
       [66.93997854],
       [46.10825774],
       [81.84535031],
       [56.69847424],
       [61.84126849],
       [56.24365113],
       [82.46967164],
       [62.837115  ],
       [53.54642993],
       [52.31022993],
       [64.91606418],
       [54.49637817],
       [60.50399464],
       [55.90237918],
       [60.48042212],
       [62.63665059],
       [74.8421485 ],
       [80.05479273],
       [69.5597103 ],
       [62.55882398],
       [54.69398748],
       [57.80915897],
       [67.62266025],
       [75.36033875],
       [61

In [190]:
X_test

Vsource.source.bus_0115.1.2.3.1  ...  Generator.geracao_pv_gmu.bus_0137_bt2.1.2.3.4.3.2
1116                        75.962776  ...                                          -0.004678
1368                        61.075089  ...                                          -0.001827
422                         54.234822  ...                                          -0.003149
413                         43.745696  ...                                          -0.000317
451                         66.020323  ...                                          -0.002290
...                               ...  ...                                                ...
352                         67.081744  ...                                          -0.003851
937                         55.440910  ...                                          -0.001667
1295                        61.737498  ...                                          -0.003282
1392                        52.945587  ...                                          -0.004289
1300                        36.391729  ...                                          -0.001839

[495 rows x 689 columns]

In [179]:
H

array([[2.73295718e-03, 7.72003997e-04, 8.29860794e-04, ...,
        5.43129227e-05, 6.06618242e-05, 5.87290554e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [154]:
ytreino=y_train.iloc[:, [1]].to_numpy()

In [155]:
biass = np.ones((X_train.shape[0],1))
phi = np.hstack((biass, X_train))
w = np.linalg.lstsq(np.matmul(phi.T,phi), np.matmul(phi.T,ytreino),rcond=None)

In [156]:
row=w[0]

In [157]:
h1=row.reshape(row.shape[1],row.shape[0])

In [158]:
H=np.vstack((h,h1))

In [160]:
H.shape

(2, 690)

In [ ]:
y_test=y_test.iloc[:, [0]].to_numpy()

In [37]:
y_train

bus_0115.1   bus_0115.2  ...  bus_0171_bt.2.1  bus_0171_bt.3.1
591   6580.148638  6580.176256  ...      -150.043223        89.956119
664   6580.483552  6580.535714  ...      -150.034745        89.964453
195   6579.685507  6579.706117  ...      -150.055143        89.944264
1240  6580.613261  6580.616584  ...      -150.030011        89.969687
1048  6580.734373  6580.708664  ...      -150.032093        89.967685
...           ...          ...  ...              ...              ...
1130  6580.309061  6580.239651  ...      -150.041525        89.958602
1294  6580.472416  6580.542220  ...      -150.034523        89.964822
860   6579.670702  6579.655742  ...      -150.054602        89.945044
1459  6579.913605  6579.987302  ...      -150.048383        89.950390
1126  6580.464707  6580.480503  ...      -150.032482        89.967356

[1005 rows x 398 columns]

In [111]:
y_test.shape

(495, 398)

In [112]:
X_train.iloc[0:3,:]

Vsource.source.bus_0115.1.2.3.1  ...  Generator.geracao_pv_gmu.bus_0137_bt2.1.2.3.4.3.2
591                        65.997193  ...                                          -0.002333
664                        53.098560  ...                                          -0.002621
195                        84.347875  ...                                          -0.003557

[3 rows x 689 columns]

In [113]:
X_train.head(5)

Vsource.source.bus_0115.1.2.3.1  ...  Generator.geracao_pv_gmu.bus_0137_bt2.1.2.3.4.3.2
591                         65.997193  ...                                          -0.002333
664                         53.098560  ...                                          -0.002621
195                         84.347875  ...                                          -0.003557
1240                        46.051347  ...                                          -0.001600
1048                        47.466006  ...                                          -0.000279

[5 rows x 689 columns]

In [80]:
y_train=y_train.iloc[:, [0]].to_numpy()

In [81]:
y_test=y_test.iloc[:, [0]].to_numpy()

In [42]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
scalerY = MinMaxScaler()

In [44]:
scalerY.fit_transform(y_train)

array([[0.50548551],
       [0.67226647],
       [0.27485488],
       ...,
       [0.26748226],
       [0.38844344],
       [0.66288201]])

In [45]:
y_train = scalerY.transform(y_train)

In [46]:
y_test = scalerY.transform(y_test)

In [47]:
scaler = MinMaxScaler()

In [48]:
scaler.fit_transform(X_train)

array([[0.52352422, 0.52706854, 0.53104243, ..., 0.4368889 , 0.53368103,
        0.41498061],
       [0.35370663, 0.35442905, 0.3629213 , ..., 0.46540669, 0.52444766,
        0.37326091],
       [0.76512103, 0.76615548, 0.76986573, ..., 0.81281443, 0.19465141,
        0.23806142],
       ...,
       [0.75402784, 0.76123657, 0.75737775, ..., 0.70127773, 0.26316468,
        0.36823256],
       [0.63165945, 0.63407372, 0.64725065, ..., 0.74759539, 0.20685194,
        0.37667524],
       [0.32137167, 0.3139355 , 0.31648889, ..., 0.66304514, 0.3211694 ,
        0.33288653]])

In [49]:
X_train = scaler.transform(X_train)

In [50]:
X_test = scaler.transform(X_test)

In [51]:
from sklearn.linear_model import LinearRegression

In [82]:
reg = LinearRegression().fit(X_train, y_train)

In [83]:
reg.coef_.shape

(1, 689)

In [84]:
reg.score(X_train, y_train)

0.9999999999994932

In [85]:
y_pred = reg.predict(X_test)

In [86]:
from sklearn.metrics import explained_variance_score

In [87]:
y_true=y_test

In [88]:
explained_variance_score(y_test, y_pred)

0.9999999999828041

In [89]:
from sklearn.metrics import max_error

In [90]:
max_error(y_true, y_pred)

1.0533622116781771e-05

In [91]:
from sklearn.metrics import mean_absolute_error

In [92]:
mean_absolute_error(y_true, y_pred)

6.99322646885941e-07

In [93]:
from sklearn.metrics import mean_squared_error

In [94]:
mean_squared_error(y_true, y_pred)

1.6276145938777176e-12

In [95]:
X_train.iloc[[0],:]

Vsource.source.bus_0115.1.2.3.1  ...  Generator.geracao_pv_gmu.bus_0137_bt2.1.2.3.4.3.2
591                        65.997193  ...                                          -0.002333

[1 rows x 689 columns]

In [96]:
X_train.head(5)

Vsource.source.bus_0115.1.2.3.1  ...  Generator.geracao_pv_gmu.bus_0137_bt2.1.2.3.4.3.2
591                         65.997193  ...                                          -0.002333
664                         53.098560  ...                                          -0.002621
195                         84.347875  ...                                          -0.003557
1240                        46.051347  ...                                          -0.001600
1048                        47.466006  ...                                          -0.000279

[5 rows x 689 columns]