<a href="https://colab.research.google.com/github/byronacunia/Linear/blob/main/Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Read Data

In [1]:
!git clone https://github.com/byronacunia/Linear.git

Cloning into 'Linear'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 17 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (17/17), done.


In [71]:
import pandas as pd

In [332]:
X =  pd.read_csv("/content/Linear/X_DF.csv")
y =  pd.read_csv("/content/Linear/Y_DF.csv")

In [333]:
X.shape

(1500, 689)

In [334]:
y.shape

(1500, 398)

In [384]:
import numpy as np
from sklearn.model_selection import train_test_split

In [385]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [386]:
H.shape

(398, 690)

In [387]:
H = np.zeros((y_train.shape[1], X_train.shape[1]+1)) # Pre-allocate matrix

In [388]:
for i in range(y_train.shape[1]):
  ytreino=y_train.iloc[:, [i]].to_numpy()
  #ytreino=y_train[:, [i]] ##Cuando se escala
  biass = np.ones((X_train.shape[0],1))
  phi = np.hstack((biass, X_train))
  w = np.linalg.lstsq(np.matmul(phi.T,phi), np.matmul(phi.T,ytreino),rcond=None)
  row=w[0]
  H[i,:] = row.T

In [389]:
y_test.shape

(495, 398)

In [390]:
#YPredictions = np.zeros((y_test.shape[1], y_test.shape[0])) # Pre-allocate matrix
RMSE=[]
from sklearn.metrics import mean_squared_error

In [391]:
i=0
xTeste=X_test.iloc[[i],:].to_numpy()
xTeste=np.vstack((1,xTeste.T))
y_pred=np.matmul(H,xTeste)
y_true = y_test.iloc[[i],:].to_numpy()
mean_squared_error(y_true.T.tolist(), y_pred.tolist())

203.5435606665843

In [382]:
np.savetxt("y_pred.csv", y_pred, delimiter=",")
y_pred

array([[ 6.57983312e+03],
       [ 6.57975339e+03],
       [ 6.57980814e+03],
       [ 6.57944253e+03],
       [ 6.57942508e+03],
       [ 6.57954636e+03],
       [ 6.57886071e+03],
       [ 6.57893603e+03],
       [ 6.57915642e+03],
       [ 6.57858490e+03],
       [ 6.57870606e+03],
       [ 6.57896529e+03],
       [ 6.57792336e+03],
       [ 6.57812278e+03],
       [ 6.57845033e+03],
       [ 6.57728753e+03],
       [ 6.57756217e+03],
       [ 6.57795540e+03],
       [ 6.57845088e+03],
       [ 6.57855356e+03],
       [ 6.57884250e+03],
       [ 6.57824197e+03],
       [ 6.57835674e+03],
       [ 6.57867738e+03],
       [ 6.57789444e+03],
       [ 6.57802932e+03],
       [ 6.57840270e+03],
       [ 6.57564559e+03],
       [ 6.57611682e+03],
       [ 6.57667304e+03],
       [ 6.57503345e+03],
       [ 6.57558046e+03],
       [ 6.57619306e+03],
       [ 6.57450541e+03],
       [ 6.57511763e+03],
       [ 6.57577812e+03],
       [ 6.57592120e+03],
       [ 6.57635831e+03],
       [ 6.5

In [380]:
y_pred[0]

array([6579.83312283])

In [379]:
y_true.T.shape

(398, 1)

In [381]:
y_true.T[0]

array([6579.833266])

In [369]:
for i in range(X_test.shape[0]):
  xTeste=X_test.iloc[[i],:].to_numpy()
  #xTeste=X_test[[i],:] #Cuando se escala
  xTeste=np.vstack((1,xTeste.T))
  y_pred=np.matmul(H,xTeste)
  y_true = y_test.iloc[[i],:].to_numpy()
  RMSE.append(mean_squared_error(y_true.T, y_pred))

In [370]:
np.max(RMSE)

408.0495075703496

In [372]:
np.mean(RMSE)

94.39244357964037

In [371]:
np.min(RMSE)

3.7596788670337986

In [373]:
RMSE[0]

203.5435606665843

In [208]:
from sklearn.metrics import explained_variance_score

In [216]:
explained_variance_score(yteste, y_pred)

0.9999801725177312

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scalerY = MinMaxScaler()
scalerY.fit_transform(y_train)
y_train = scalerY.transform(y_train)
y_test = scalerY.transform(y_test)
scaler = MinMaxScaler()
scaler.fit_transform(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [80]:
y_train=y_train.iloc[:, [0]].to_numpy()

In [81]:
y_test=y_test.iloc[:, [0]].to_numpy()

In [42]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
scalerY = MinMaxScaler()

In [44]:
scalerY.fit_transform(y_train)

array([[0.50548551],
       [0.67226647],
       [0.27485488],
       ...,
       [0.26748226],
       [0.38844344],
       [0.66288201]])

In [45]:
y_train = scalerY.transform(y_train)

In [46]:
y_test = scalerY.transform(y_test)

In [47]:
scaler = MinMaxScaler()

In [48]:
scaler.fit_transform(X_train)

array([[0.52352422, 0.52706854, 0.53104243, ..., 0.4368889 , 0.53368103,
        0.41498061],
       [0.35370663, 0.35442905, 0.3629213 , ..., 0.46540669, 0.52444766,
        0.37326091],
       [0.76512103, 0.76615548, 0.76986573, ..., 0.81281443, 0.19465141,
        0.23806142],
       ...,
       [0.75402784, 0.76123657, 0.75737775, ..., 0.70127773, 0.26316468,
        0.36823256],
       [0.63165945, 0.63407372, 0.64725065, ..., 0.74759539, 0.20685194,
        0.37667524],
       [0.32137167, 0.3139355 , 0.31648889, ..., 0.66304514, 0.3211694 ,
        0.33288653]])

In [49]:
X_train = scaler.transform(X_train)

In [50]:
X_test = scaler.transform(X_test)

In [51]:
from sklearn.linear_model import LinearRegression

In [82]:
reg = LinearRegression().fit(X_train, y_train)

In [83]:
reg.coef_.shape

(1, 689)

In [84]:
reg.score(X_train, y_train)

0.9999999999994932

In [85]:
y_pred = reg.predict(X_test)

In [86]:
from sklearn.metrics import explained_variance_score

In [87]:
y_true=y_test

In [88]:
explained_variance_score(y_test, y_pred)

0.9999999999828041

In [89]:
from sklearn.metrics import max_error

In [90]:
max_error(y_true, y_pred)

1.0533622116781771e-05

In [91]:
from sklearn.metrics import mean_absolute_error

In [92]:
mean_absolute_error(y_true, y_pred)

6.99322646885941e-07

1.6276145938777176e-12

In [95]:
X_train.iloc[[0],:]

Vsource.source.bus_0115.1.2.3.1  ...  Generator.geracao_pv_gmu.bus_0137_bt2.1.2.3.4.3.2
591                        65.997193  ...                                          -0.002333

[1 rows x 689 columns]

In [96]:
X_train.head(5)

Vsource.source.bus_0115.1.2.3.1  ...  Generator.geracao_pv_gmu.bus_0137_bt2.1.2.3.4.3.2
591                         65.997193  ...                                          -0.002333
664                         53.098560  ...                                          -0.002621
195                         84.347875  ...                                          -0.003557
1240                        46.051347  ...                                          -0.001600
1048                        47.466006  ...                                          -0.000279

[5 rows x 689 columns]