<a href="https://colab.research.google.com/github/byronacunia/Linear/blob/main/Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Read Data

In [1]:
!git clone https://github.com/byronacunia/Linear.git

Cloning into 'Linear'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 53 (delta 15), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (53/53), done.


In [35]:
import pandas as pd

In [36]:
X =  pd.read_csv("/content/Linear/X_DF.csv")
y =  pd.read_csv("/content/Linear/Y_Vmag_DF.csv")

In [37]:
X.shape

(1500, 689)

In [38]:
y.shape

(1500, 156)

In [39]:
import numpy as np
from sklearn.model_selection import train_test_split

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [41]:
X_train.shape

(1005, 689)

In [42]:
H = np.zeros((y_train.shape[1], X_train.shape[1]+1)) # Pre-allocate matrix

In [43]:
from sklearn.linear_model import LinearRegression

In [44]:
for i in range(y_train.shape[1]):
  ytreino=y_train.iloc[:, [i]].to_numpy()
  lr = LinearRegression()
  lr.fit(X_train, ytreino)
  coef=lr.coef_
  bias=lr.intercept_
  row = np.hstack((bias.reshape(1,1),coef))
  H[i,:] = row

In [45]:
MSE=[]
from sklearn.metrics import mean_squared_error

In [46]:
for i in range(X_test.shape[0]):
  xTeste=X_test.iloc[[i],:].to_numpy()
  #xTeste=X_test[[i],:] #Cuando se escala
  xTeste=np.vstack((1,xTeste.T))
  y_pred=np.matmul(H,xTeste)
  y_true = y_test.iloc[[i],:].to_numpy()
  MSE.append(mean_squared_error(y_true.T, y_pred))

In [47]:
np.max(MSE)

1798.1476983115776

In [48]:
np.mean(MSE)

18.014540555413305

In [49]:
np.min(MSE)

0.03323445761870875

In [50]:
for i in range(y_train.shape[1]):
  ytreino=y_train.iloc[:, [i]].to_numpy()
  #ytreino=y_train[:, [i]] ##Cuando se escala
  biass = np.ones((X_train.shape[0],1))
  phi = np.hstack((biass, X_train))
  w = np.linalg.lstsq(np.matmul(phi.T,phi), np.matmul(phi.T,ytreino),rcond=None)
  row=w[0]
  H[i,:] = row.T

In [51]:
#YPredictions = np.zeros((y_test.shape[1], y_test.shape[0])) # Pre-allocate matrix
MSE=[]
from sklearn.metrics import mean_squared_error

In [52]:
for i in range(X_test.shape[0]):
  xTeste=X_test.iloc[[i],:].to_numpy()
  #xTeste=X_test[[i],:] #Cuando se escala
  xTeste=np.vstack((1,xTeste.T))
  y_pred=np.matmul(H,xTeste)
  y_true = y_test.iloc[[i],:].to_numpy()
  MSE.append(mean_squared_error(y_true.T, y_pred))
  

In [53]:
np.max(MSE)

27.870505883848626

In [54]:
np.mean(MSE)

2.167625965115265

In [55]:
np.min(MSE)

0.0071578550626425815

In [56]:
aux=np.array(MSE)

In [59]:
aux = aux.reshape(aux.shape[0],1)

In [60]:
aux1 = np.hstack((aux,aux))

In [61]:
aux1.shape

(495, 2)

In [62]:
aux1

array([[8.72402075e-01, 8.72402075e-01],
       [4.60518108e-01, 4.60518108e-01],
       [1.57116398e-01, 1.57116398e-01],
       [2.06262173e+00, 2.06262173e+00],
       [2.28671317e+00, 2.28671317e+00],
       [1.46963209e-01, 1.46963209e-01],
       [6.91541462e-02, 6.91541462e-02],
       [6.09404323e-01, 6.09404323e-01],
       [2.14470813e-02, 2.14470813e-02],
       [1.41831556e-01, 1.41831556e-01],
       [1.81154872e+00, 1.81154872e+00],
       [3.75546108e+00, 3.75546108e+00],
       [3.04090505e+00, 3.04090505e+00],
       [1.73454653e+00, 1.73454653e+00],
       [3.94785361e-01, 3.94785361e-01],
       [2.14568351e-01, 2.14568351e-01],
       [4.24527642e-02, 4.24527642e-02],
       [1.88640518e+00, 1.88640518e+00],
       [3.72142815e+00, 3.72142815e+00],
       [2.78821893e-02, 2.78821893e-02],
       [8.67293037e-02, 8.67293037e-02],
       [1.13399790e+00, 1.13399790e+00],
       [4.91855342e-01, 4.91855342e-01],
       [1.34611727e-02, 1.34611727e-02],
       [2.297183

In [208]:
from sklearn.metrics import explained_variance_score

In [216]:
explained_variance_score(yteste, y_pred)

0.9999801725177312

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scalerY = MinMaxScaler()
scalerY.fit_transform(y_train)
y_train = scalerY.transform(y_train)
y_test = scalerY.transform(y_test)
scaler = MinMaxScaler()
scaler.fit_transform(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [80]:
y_train=y_train.iloc[:, [0]].to_numpy()

In [81]:
y_test=y_test.iloc[:, [0]].to_numpy()

In [42]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
scalerY = MinMaxScaler()

In [44]:
scalerY.fit_transform(y_train)

array([[0.50548551],
       [0.67226647],
       [0.27485488],
       ...,
       [0.26748226],
       [0.38844344],
       [0.66288201]])

In [45]:
y_train = scalerY.transform(y_train)

In [46]:
y_test = scalerY.transform(y_test)

In [47]:
scaler = MinMaxScaler()

In [48]:
scaler.fit_transform(X_train)

array([[0.52352422, 0.52706854, 0.53104243, ..., 0.4368889 , 0.53368103,
        0.41498061],
       [0.35370663, 0.35442905, 0.3629213 , ..., 0.46540669, 0.52444766,
        0.37326091],
       [0.76512103, 0.76615548, 0.76986573, ..., 0.81281443, 0.19465141,
        0.23806142],
       ...,
       [0.75402784, 0.76123657, 0.75737775, ..., 0.70127773, 0.26316468,
        0.36823256],
       [0.63165945, 0.63407372, 0.64725065, ..., 0.74759539, 0.20685194,
        0.37667524],
       [0.32137167, 0.3139355 , 0.31648889, ..., 0.66304514, 0.3211694 ,
        0.33288653]])

In [49]:
X_train = scaler.transform(X_train)

In [50]:
X_test = scaler.transform(X_test)

In [51]:
from sklearn.linear_model import LinearRegression

In [82]:
reg = LinearRegression().fit(X_train, y_train)

In [83]:
reg.coef_.shape

(1, 689)

In [84]:
reg.score(X_train, y_train)

0.9999999999994932

In [85]:
y_pred = reg.predict(X_test)

In [86]:
from sklearn.metrics import explained_variance_score

In [87]:
y_true=y_test

In [88]:
explained_variance_score(y_test, y_pred)

0.9999999999828041

In [89]:
from sklearn.metrics import max_error

In [90]:
max_error(y_true, y_pred)

1.0533622116781771e-05

In [91]:
from sklearn.metrics import mean_absolute_error

In [92]:
mean_absolute_error(y_true, y_pred)

6.99322646885941e-07

1.6276145938777176e-12

In [95]:
X_train.iloc[[0],:]

Vsource.source.bus_0115.1.2.3.1  ...  Generator.geracao_pv_gmu.bus_0137_bt2.1.2.3.4.3.2
591                        65.997193  ...                                          -0.002333

[1 rows x 689 columns]

In [96]:
X_train.head(5)

Vsource.source.bus_0115.1.2.3.1  ...  Generator.geracao_pv_gmu.bus_0137_bt2.1.2.3.4.3.2
591                         65.997193  ...                                          -0.002333
664                         53.098560  ...                                          -0.002621
195                         84.347875  ...                                          -0.003557
1240                        46.051347  ...                                          -0.001600
1048                        47.466006  ...                                          -0.000279

[5 rows x 689 columns]